[project]
name = "djereo-docs"
version = "3.18.0"
description = ""
authors = [
    {name = "Alberto Morón Hernández", email = "alberto.moronh@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1,<2.0.0",
]
